language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"
install: "python setup.py install"
script:
  - adles -h
  - adles --version
  - adles -v --check-syntax examples/tutorial.yaml
  - adles --no-color -v -c examples/tutorial.yaml
  - adles -v -c examples/competition.yaml
  - adles --verbose --check-syntax examples/experiment.yaml
  - clone-vms -h
  - cleanup-vms --help
  - vm-power -h
  - vsphere-info -h
  - vsphere-testing -h
  - clone-vms --version
  - cleanup-vms --version
  - vm-power --version
  - vsphere-info --version
  - vsphere-testing --version
notifications:
  email:
    on_success: never
    on_failure: always