language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy3"
install: "pip install -r requirements.txt"
script:
  - python main.py --check-syntax examples/tutorial.yaml
  - python main.py --check-syntax examples/competition.yaml
  - python main.py --check-syntax examples/experiment.yaml
notifications:
  email: false