language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"
install: "pip install -r requirements.txt"
script:
  - python main.py -h
  - python main.py --version
  - python main.py --version
  - python main.py -v --check-syntax examples/tutorial.yaml
  - python main.py --no-color -v -c examples/tutorial.yaml
  - python main.py -v -c examples/competition.yaml
  - python main.py --verbose --check-syntax examples/experiment.yaml
  - python clone_vms.py -h
  - python cleanup_vms.py --help
  - python vm_power.py -h
  - python vsphere_info.py -h
  - python vsphere_testing.py -h
  - python clone_vms.py --version
  - python cleanup_vms.py --version
  - python vm_power.py --version
  - python vsphere_info.py --version
  - python vsphere_testing.py --version
notifications:
  email:
    on_success: never
    on_failure: always