sudo: required
language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy"
    - "pypy3"
install: "sudo python setup.py install"
script:
  - python adles -h
  - python adles --version
  - python adles -v --check-syntax examples/tutorial.yaml
  - python adles --no-color -v -c examples/tutorial.yaml
  - python adles -v -c examples/competition.yaml
  - python adles --verbose --check-syntax examples/experiment.yaml
  - python clone-vms -h
  - python cleanup-vms --help
  - python vm-power -h
  - python vsphere-info -h
  - python vsphere-testing -h
  - python clone-vms --version
  - python cleanup-vms --version
  - python vm-power --version
  - python vsphere-info --version
  - python vsphere-testing --version
notifications:
  email:
    on_success: never
    on_failure: always